# Site settings
title: "Transdeco"
email:
author:
description: "Taidegalleria ja taidegrafiikan verkkokauppa"
url:

# Build settings
#permalink: :title/
sass:
  sass_dir: assets/css

# Social icons
show_social_icons: true
github_username: someGithubUser
twitter_username: someTwitterUser

# Configuration options
exclude: [pub.sh]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-strapi
#  - jekyll-sitemap
#  - jekyll-seo-tag

# Collections
collections_dir: collections
collections:
  animals:
    permalink: animals/:name
    layout: animal
    output: true

# Strapi
strapi:
  # Your API endpoint (optional, default to http://localhost:1337)
  endpoint: http://localhost:1337
  #endpoint: https://strapi.transdeco.fi
  collections:

    # Collections
    artists:
      type: artists
      permalink: /artists/:tunniste
      layout: artist.html
      output: true
    works:
      type: works
      permalink: /works/:tunniste
      layout: work.html
      output: true
    singles:
      type: singles
      permalink: /:tunniste
      layout: singles.html
      output: true
